import {
    KeyGlamorousComponentFactory,
    GlamorousOptions,
    CSSProperties,
    SVGProperties,
    PropsAreCssOverridesGlamorousOptions,
    KeyGlamorousComponentFactoryCssOverides,
} from './glamorous'

export interface DOMTagGlamorousComponentFactory<DomTag extends keyof JSX.IntrinsicElements>  {
    <ExternalProps, Context = object, DefaultProps extends object = object>(
        component: DomTag,
        options?: Partial<GlamorousOptions<ExternalProps, Context, DefaultProps>>,
    ): KeyGlamorousComponentFactory<
        JSX.IntrinsicElements[DomTag], CSSProperties, ExternalProps, DefaultProps
    >

    <ExternalProps, Context = object, DefaultProps extends object = object>(
        component: DomTag,
        options?: PropsAreCssOverridesGlamorousOptions<ExternalProps, Context, DefaultProps>,
    ): KeyGlamorousComponentFactoryCssOverides<
        JSX.IntrinsicElements[DomTag], CSSProperties, ExternalProps, DefaultProps
    >
}

export interface SVGTagGlamorousComponentFactory<DomTag extends keyof JSX.IntrinsicElements>  {
    <ExternalProps, Context = object, DefaultProps extends object = object>(
        component: DomTag,
        options?: Partial<GlamorousOptions<ExternalProps, Context, DefaultProps>>,
    ): KeyGlamorousComponentFactory<
        JSX.IntrinsicElements[DomTag], SVGProperties, ExternalProps, DefaultProps
    >

    <ExternalProps, Context = object, DefaultProps extends object = object>(
        component: DomTag,
        options?: PropsAreCssOverridesGlamorousOptions<ExternalProps, Context, DefaultProps>,
    ): KeyGlamorousComponentFactoryCssOverides<
        JSX.IntrinsicElements[DomTag], SVGProperties, ExternalProps, DefaultProps
    >
}

export interface DOMTagComponentFactory extends
    DOMTagGlamorousComponentFactory<'a'>,
    DOMTagGlamorousComponentFactory<'a'>,
    DOMTagGlamorousComponentFactory<'abbr'>,
    DOMTagGlamorousComponentFactory<'address'>,
    DOMTagGlamorousComponentFactory<'area'>,
    DOMTagGlamorousComponentFactory<'article'>,
    DOMTagGlamorousComponentFactory<'aside'>,
    DOMTagGlamorousComponentFactory<'audio'>,
    DOMTagGlamorousComponentFactory<'b'>,
    DOMTagGlamorousComponentFactory<'base'>,
    DOMTagGlamorousComponentFactory<'bdi'>,
    DOMTagGlamorousComponentFactory<'bdo'>,
    DOMTagGlamorousComponentFactory<'big'>,
    DOMTagGlamorousComponentFactory<'blockquote'>,
    DOMTagGlamorousComponentFactory<'body'>,
    DOMTagGlamorousComponentFactory<'br'>,
    DOMTagGlamorousComponentFactory<'button'>,
    DOMTagGlamorousComponentFactory<'canvas'>,
    DOMTagGlamorousComponentFactory<'caption'>,
    DOMTagGlamorousComponentFactory<'cite'>,
    DOMTagGlamorousComponentFactory<'code'>,
    DOMTagGlamorousComponentFactory<'col'>,
    DOMTagGlamorousComponentFactory<'colgroup'>,
    DOMTagGlamorousComponentFactory<'data'>,
    DOMTagGlamorousComponentFactory<'datalist'>,
    DOMTagGlamorousComponentFactory<'dd'>,
    DOMTagGlamorousComponentFactory<'del'>,
    DOMTagGlamorousComponentFactory<'details'>,
    DOMTagGlamorousComponentFactory<'dfn'>,
    DOMTagGlamorousComponentFactory<'dialog'>,
    DOMTagGlamorousComponentFactory<'div'>,
    DOMTagGlamorousComponentFactory<'dl'>,
    DOMTagGlamorousComponentFactory<'dt'>,
    DOMTagGlamorousComponentFactory<'em'>,
    DOMTagGlamorousComponentFactory<'embed'>,
    DOMTagGlamorousComponentFactory<'fieldset'>,
    DOMTagGlamorousComponentFactory<'figcaption'>,
    DOMTagGlamorousComponentFactory<'figure'>,
    DOMTagGlamorousComponentFactory<'footer'>,
    DOMTagGlamorousComponentFactory<'form'>,
    DOMTagGlamorousComponentFactory<'h1'>,
    DOMTagGlamorousComponentFactory<'h2'>,
    DOMTagGlamorousComponentFactory<'h3'>,
    DOMTagGlamorousComponentFactory<'h4'>,
    DOMTagGlamorousComponentFactory<'h5'>,
    DOMTagGlamorousComponentFactory<'h6'>,
    DOMTagGlamorousComponentFactory<'head'>,
    DOMTagGlamorousComponentFactory<'header'>,
    DOMTagGlamorousComponentFactory<'hgroup'>,
    DOMTagGlamorousComponentFactory<'hr'>,
    DOMTagGlamorousComponentFactory<'html'>,
    DOMTagGlamorousComponentFactory<'i'>,
    DOMTagGlamorousComponentFactory<'iframe'>,
    DOMTagGlamorousComponentFactory<'img'>,
    DOMTagGlamorousComponentFactory<'input'>,
    DOMTagGlamorousComponentFactory<'ins'>,
    DOMTagGlamorousComponentFactory<'kbd'>,
    DOMTagGlamorousComponentFactory<'keygen'>,
    DOMTagGlamorousComponentFactory<'label'>,
    DOMTagGlamorousComponentFactory<'legend'>,
    DOMTagGlamorousComponentFactory<'li'>,
    DOMTagGlamorousComponentFactory<'link'>,
    DOMTagGlamorousComponentFactory<'main'>,
    DOMTagGlamorousComponentFactory<'map'>,
    DOMTagGlamorousComponentFactory<'mark'>,
    DOMTagGlamorousComponentFactory<'menu'>,
    DOMTagGlamorousComponentFactory<'menuitem'>,
    DOMTagGlamorousComponentFactory<'meta'>,
    DOMTagGlamorousComponentFactory<'meter'>,
    DOMTagGlamorousComponentFactory<'nav'>,
    DOMTagGlamorousComponentFactory<'noscript'>,
    DOMTagGlamorousComponentFactory<'object'>,
    DOMTagGlamorousComponentFactory<'ol'>,
    DOMTagGlamorousComponentFactory<'optgroup'>,
    DOMTagGlamorousComponentFactory<'option'>,
    DOMTagGlamorousComponentFactory<'output'>,
    DOMTagGlamorousComponentFactory<'p'>,
    DOMTagGlamorousComponentFactory<'param'>,
    DOMTagGlamorousComponentFactory<'picture'>,
    DOMTagGlamorousComponentFactory<'pre'>,
    DOMTagGlamorousComponentFactory<'progress'>,
    DOMTagGlamorousComponentFactory<'q'>,
    DOMTagGlamorousComponentFactory<'rp'>,
    DOMTagGlamorousComponentFactory<'rt'>,
    DOMTagGlamorousComponentFactory<'ruby'>,
    DOMTagGlamorousComponentFactory<'s'>,
    DOMTagGlamorousComponentFactory<'samp'>,
    DOMTagGlamorousComponentFactory<'script'>,
    DOMTagGlamorousComponentFactory<'section'>,
    DOMTagGlamorousComponentFactory<'select'>,
    DOMTagGlamorousComponentFactory<'small'>,
    DOMTagGlamorousComponentFactory<'source'>,
    DOMTagGlamorousComponentFactory<'span'>,
    DOMTagGlamorousComponentFactory<'strong'>,
    DOMTagGlamorousComponentFactory<'style'>,
    DOMTagGlamorousComponentFactory<'sub'>,
    DOMTagGlamorousComponentFactory<'summary'>,
    DOMTagGlamorousComponentFactory<'sup'>,
    DOMTagGlamorousComponentFactory<'table'>,
    DOMTagGlamorousComponentFactory<'tbody'>,
    DOMTagGlamorousComponentFactory<'td'>,
    DOMTagGlamorousComponentFactory<'textarea'>,
    DOMTagGlamorousComponentFactory<'tfoot'>,
    DOMTagGlamorousComponentFactory<'th'>,
    DOMTagGlamorousComponentFactory<'thead'>,
    DOMTagGlamorousComponentFactory<'time'>,
    DOMTagGlamorousComponentFactory<'title'>,
    DOMTagGlamorousComponentFactory<'tr'>,
    DOMTagGlamorousComponentFactory<'track'>,
    DOMTagGlamorousComponentFactory<'u'>,
    DOMTagGlamorousComponentFactory<'ul'>,
    DOMTagGlamorousComponentFactory<'var'>,
    DOMTagGlamorousComponentFactory<'video'>,
    DOMTagGlamorousComponentFactory<'wbr'>
        {}

export interface SVGTagComponentFactory extends
    SVGTagGlamorousComponentFactory<'circle'>,
    SVGTagGlamorousComponentFactory<'clipPath'>,
    SVGTagGlamorousComponentFactory<'defs'>,
    SVGTagGlamorousComponentFactory<'ellipse'>,
    SVGTagGlamorousComponentFactory<'g'>,
    SVGTagGlamorousComponentFactory<'image'>,
    SVGTagGlamorousComponentFactory<'line'>,
    SVGTagGlamorousComponentFactory<'linearGradient'>,
    SVGTagGlamorousComponentFactory<'mask'>,
    SVGTagGlamorousComponentFactory<'path'>,
    SVGTagGlamorousComponentFactory<'pattern'>,
    SVGTagGlamorousComponentFactory<'polygon'>,
    SVGTagGlamorousComponentFactory<'polyline'>,
    SVGTagGlamorousComponentFactory<'radialGradient'>,
    SVGTagGlamorousComponentFactory<'rect'>,
    SVGTagGlamorousComponentFactory<'stop'>,
    SVGTagGlamorousComponentFactory<'svg'>,
    SVGTagGlamorousComponentFactory<'text'>,
    SVGTagGlamorousComponentFactory<'tspan'>
        {}
