import { CSSProperties, SVGAttributes } from 'react'

import { StyledFunction } from './glamorous'

export interface HTMLGlamorousInterface {
    a: StyledFunction<CSSProperties>
    abbr: StyledFunction<CSSProperties>
    address: StyledFunction<CSSProperties>
    area: StyledFunction<CSSProperties>
    article: StyledFunction<CSSProperties>
    aside: StyledFunction<CSSProperties>
    audio: StyledFunction<CSSProperties>
    b: StyledFunction<CSSProperties>
    base: StyledFunction<CSSProperties>
    bdi: StyledFunction<CSSProperties>
    bdo: StyledFunction<CSSProperties>
    big: StyledFunction<CSSProperties>
    blockquote: StyledFunction<CSSProperties>
    body: StyledFunction<CSSProperties>
    br: StyledFunction<CSSProperties>
    button: StyledFunction<CSSProperties>
    canvas: StyledFunction<CSSProperties>
    caption: StyledFunction<CSSProperties>
    cite: StyledFunction<CSSProperties>
    code: StyledFunction<CSSProperties>
    col: StyledFunction<CSSProperties>
    colgroup: StyledFunction<CSSProperties>
    data: StyledFunction<CSSProperties>
    datalist: StyledFunction<CSSProperties>
    dd: StyledFunction<CSSProperties>
    del: StyledFunction<CSSProperties>
    details: StyledFunction<CSSProperties>
    dfn: StyledFunction<CSSProperties>
    dialog: StyledFunction<CSSProperties>
    div: StyledFunction<CSSProperties>
    dl: StyledFunction<CSSProperties>
    dt: StyledFunction<CSSProperties>
    em: StyledFunction<CSSProperties>
    embed: StyledFunction<CSSProperties>
    fieldset: StyledFunction<CSSProperties>
    figcaption: StyledFunction<CSSProperties>
    figure: StyledFunction<CSSProperties>
    footer: StyledFunction<CSSProperties>
    form: StyledFunction<CSSProperties>
    h1: StyledFunction<CSSProperties>
    h2: StyledFunction<CSSProperties>
    h3: StyledFunction<CSSProperties>
    h4: StyledFunction<CSSProperties>
    h5: StyledFunction<CSSProperties>
    h6: StyledFunction<CSSProperties>
    head: StyledFunction<CSSProperties>
    header: StyledFunction<CSSProperties>
    hgroup: StyledFunction<CSSProperties>
    hr: StyledFunction<CSSProperties>
    html: StyledFunction<CSSProperties>
    i: StyledFunction<CSSProperties>
    iframe: StyledFunction<CSSProperties>
    img: StyledFunction<CSSProperties>
    input: StyledFunction<CSSProperties>
    ins: StyledFunction<CSSProperties>
    kbd: StyledFunction<CSSProperties>
    keygen: StyledFunction<CSSProperties>
    label: StyledFunction<CSSProperties>
    legend: StyledFunction<CSSProperties>
    li: StyledFunction<CSSProperties>
    link: StyledFunction<CSSProperties>
    main: StyledFunction<CSSProperties>
    map: StyledFunction<CSSProperties>
    mark: StyledFunction<CSSProperties>
    menu: StyledFunction<CSSProperties>
    menuitem: StyledFunction<CSSProperties>
    meta: StyledFunction<CSSProperties>
    meter: StyledFunction<CSSProperties>
    nav: StyledFunction<CSSProperties>
    noscript: StyledFunction<CSSProperties>
    object: StyledFunction<CSSProperties>
    ol: StyledFunction<CSSProperties>
    optgroup: StyledFunction<CSSProperties>
    option: StyledFunction<CSSProperties>
    output: StyledFunction<CSSProperties>
    p: StyledFunction<CSSProperties>
    param: StyledFunction<CSSProperties>
    picture: StyledFunction<CSSProperties>
    pre: StyledFunction<CSSProperties>
    progress: StyledFunction<CSSProperties>
    q: StyledFunction<CSSProperties>
    rp: StyledFunction<CSSProperties>
    rt: StyledFunction<CSSProperties>
    ruby: StyledFunction<CSSProperties>
    s: StyledFunction<CSSProperties>
    samp: StyledFunction<CSSProperties>
    script: StyledFunction<CSSProperties>
    section: StyledFunction<CSSProperties>
    select: StyledFunction<CSSProperties>
    small: StyledFunction<CSSProperties>
    source: StyledFunction<CSSProperties>
    span: StyledFunction<CSSProperties>
    strong: StyledFunction<CSSProperties>
    style: StyledFunction<CSSProperties>
    sub: StyledFunction<CSSProperties>
    summary: StyledFunction<CSSProperties>
    sup: StyledFunction<CSSProperties>
    table: StyledFunction<CSSProperties>
    tbody: StyledFunction<CSSProperties>
    td: StyledFunction<CSSProperties>
    textarea: StyledFunction<CSSProperties>
    tfoot: StyledFunction<CSSProperties>
    th: StyledFunction<CSSProperties>
    thead: StyledFunction<CSSProperties>
    time: StyledFunction<CSSProperties>
    title: StyledFunction<CSSProperties>
    tr: StyledFunction<CSSProperties>
    track: StyledFunction<CSSProperties>
    u: StyledFunction<CSSProperties>
    ul: StyledFunction<CSSProperties>
    var: StyledFunction<CSSProperties>
    video: StyledFunction<CSSProperties>
    wbr: StyledFunction<CSSProperties>
}


export interface SVGGlamorousInterface {
    svg: StyledFunction<SVGAttributes<any>>
}
