import * as React from 'react'
import { ExtraGlamorousProps } from './glamorous-component';
import { CSSProperties } from './css-properties';

// This file is based off `./built-in-glamorous-components.d.ts`

export const A: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['a']>
export const Abbr: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['abbr']>
export const Address: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['address']>
export const Area: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['area']>
export const Article: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['article']>
export const Aside: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['aside']>
export const Audio: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['audio']>
export const B: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['b']>
export const Base: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['base']>
export const Bdi: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['bdi']>
export const Bdo: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['bdo']>
export const Big: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['big']>
export const Blockquote: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['blockquote']>
export const Body: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['body']>
export const Br: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['br']>
export const Button: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['button']>
export const Canvas: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['canvas']>
export const Caption: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['caption']>
export const Cite: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['cite']>
export const Code: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['code']>
export const Col: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['col']>
export const Colgroup: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['colgroup']>
export const Data: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['data']>
export const Datalist: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['datalist']>
export const Dd: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['dd']>
export const Del: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['del']>
export const Details: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['details']>
export const Dfn: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['dfn']>
export const Dialog: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['dialog']>
export const Div: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['div']>
export const Dl: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['dl']>
export const Dt: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['dt']>
export const Em: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['em']>
export const Embed: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['embed']>
export const Fieldset: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['fieldset']>
export const Figcaption: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['figcaption']>
export const Figure: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['figure']>
export const Footer: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['footer']>
export const Form: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['form']>
export const H1: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['h1']>
export const H2: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['h2']>
export const H3: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['h3']>
export const H4: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['h4']>
export const H5: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['h5']>
export const H6: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['h6']>
export const Head: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['head']>
export const Header: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['header']>
export const Hgroup: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['hgroup']>
export const Hr: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['hr']>
export const Html: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['html']>
export const I: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['i']>
export const Iframe: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['iframe']>
export const Img: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['img']>
export const Input: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['input']>
export const Ins: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['ins']>
export const Kbd: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['kbd']>
export const Keygen: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['keygen']>
export const Label: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['label']>
export const Legend: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['legend']>
export const Li: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['li']>
export const Link: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['link']>
export const Main: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['main']>
export const Map: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['map']>
export const Mark: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['mark']>
export const Menu: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['menu']>
export const Menuitem: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['menuitem']>
export const Meta: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['meta']>
export const Meter: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['meter']>
export const Nav: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['nav']>
export const Noscript: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['noscript']>
export const Object: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['object']>
export const Ol: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['ol']>
export const Optgroup: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['optgroup']>
export const Option: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['option']>
export const Output: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['output']>
export const P: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['p']>
export const Param: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['param']>
export const Picture: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['picture']>
export const Pre: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['pre']>
export const Progress: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['progress']>
export const Q: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['q']>
export const Rp: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['rp']>
export const Rt: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['rt']>
export const Ruby: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['ruby']>
export const S: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['s']>
export const Samp: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['samp']>
export const Script: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['script']>
export const Section: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['section']>
export const Select: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['select']>
export const Small: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['small']>
export const Source: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['source']>
export const Span: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['span']>
export const Strong: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['strong']>
export const Style: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['style']>
export const Sub: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['sub']>
export const Summary: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['summary']>
export const Sup: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['sup']>
export const Table: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['table']>
export const Tbody: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['tbody']>
export const Td: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['td']>
export const Textarea: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['textarea']>
export const Tfoot: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['tfoot']>
export const Th: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['th']>
export const Thead: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['thead']>
export const Time: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['time']>
export const Title: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['title']>
export const Tr: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['tr']>
export const Track: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['track']>
export const U: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['u']>
export const Ul: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['ul']>
export const Var: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['var']>
export const Video: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['video']>
export const Wbr: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['wbr']>
export const Circle: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['circle']>
export const ClipPath: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['clipPath']>
export const Defs: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['defs']>
export const Ellipse: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['ellipse']>
export const G: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['g']>
export const Image: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['image']>
export const Line: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['line']>
export const LinearGradient: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['linearGradient']>
export const Mask: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['mask']>
export const Path: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['path']>
export const Pattern: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['pattern']>
export const Polygon: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['polygon']>
export const Polyline: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['polyline']>
export const RadialGradient: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['radialGradient']>
export const Rect: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['rect']>
export const Stop: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['stop']>
export const Svg: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['svg']>
export const Text: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['text']>
export const Tspan: React.StatelessComponent<CSSProperties & ExtraGlamorousProps & JSX.IntrinsicElements['tspan']>
